apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstapp-v1-deployment
  namespace: firstapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstapp-web-v1
  template:
    metadata:
      labels:
        app: firstapp-web-v1
    spec:
      containers:
      - name: firstapp-v1
        image: 149536497934.dkr.ecr.ap-south-1.amazonaws.com/firstapp:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: firstapp-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: firstapp-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: firstapp-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: firstapp-secret
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: firstapp-config
              key: DB_PORT
        #readinessProbe:
          #httpGet:
            #path: /healthz          #App code must have this path set
            #port: 3000
          #initialDelaySeconds: 5
          #periodSeconds: 5
          #timeoutSeconds: 2
          #failureThreshold: 3
          #successThreshold: 1
        livenessProbe:
          httpGet:
            path: /livez            #App code must have this path set
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        resources:
          requests:
            cpu: "30m"
            memory: "100Mi"
          limits:
            cpu: "60m"
            memory: "200Mi"


---

apiVersion: v1
kind: Service
metadata:
  name: firstapp-v1-service
  namespace: firstapp
spec:
  selector:
    app: firstapp-web-v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  #type: ClusterIP     #Only for Fargate type of EKS
  type: NodePort      #For EC2-node type of eks , alb look for node-ip's to target it to.