apiVersion: apps/v1
kind: Deployment
metadata:
  name: thirdapp-deployment
  namespace: firstapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thirdapp-web
  template:
    metadata:
      labels:
        app: thirdapp-web
    spec:
      containers:
      - name: thirdapp
        image: 149536497934.dkr.ecr.ap-south-1.amazonaws.com/thirdapp:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: firstapp-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: firstapp-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: firstapp-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: firstapp-secret
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: firstapp-config
              key: DB_PORT

---

apiVersion: v1
kind: Service
metadata:
  name: thirdapp-service
  namespace: firstapp
spec:
  selector:
    app: thirdapp-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  #type: ClusterIP     #Only for Fargate type of EKS
  type: NodePort      #For EC2-node type of eks , alb look for node-ip's to target it to.