apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondapp-deployment
  namespace: secondapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secondapp-web
  template:
    metadata:
      labels:
        app: secondapp-web
    spec:
      containers:
      - name: secondapp
        image: 149536497934.dkr.ecr.ap-south-1.amazonaws.com/secondapp:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: secondapp-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secondapp-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secondapp-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: secondapp-secret
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: secondapp-config
              key: DB_PORT

---

apiVersion: v1
kind: Service
metadata:
  name: secondapp-service
  namespace: secondapp
spec:
  selector:
    app: secondapp-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  #type: ClusterIP     #Only for Fargate type of EKS
  type: NodePort      #For EC2-node type of eks , alb look for node-ip's to target it to.